### ISSUE TITLE
[Issue #4] 구

### ISSUE THREAD

**Issue by JunoJunho** [JunoJunho/MathProject#4]
- Input: 원의 반지름
- Output: 구의 부피와 표면적

**Comment by JiyoungSong1213** [comment]
SoS 화이팅!

**Comment by BaekHorang** [comment]
![sphere_and_ball](https://cloud.githubusercontent.com/assets/14369495/12636996/30e6b72c-c5d5-11e5-9169-03adece49de2.png) @JiyoungSong1213

**Comment by JunoJunho** [comment]
Assign this issue to @JiyoungSong1213
